apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaser-backend
  namespace: grupp1
  labels:
    app: yaser-guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yaser-backend
  template:
    metadata:
      labels:
        app: yaser-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/ysalha2003/yaser-guestbook-argocd/backend:d24b261ab0708edb5dcf2a9c92d21925f06be068
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: yaser-postgresql
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: yaser-postgresql-secret
              key: POSTGRESQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yaser-postgresql-secret
              key: POSTGRESQL_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: yaser-postgresql-secret
              key: POSTGRESQL_DATABASE
        - name: REDIS_HOST
          value: yaser-redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: yaser-redis-secret
              key: REDIS_PASSWORD
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 192Mi
            cpu: 400m
          requests:
            memory: 96Mi
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: yaser-backend
  namespace: grupp1
spec:
  ports:
  - port: 8080
  selector:
    app: yaser-backend
