apiVersion: apps/v1
kind: Deployment
metadata:
  name: yaser-frontend
  namespace: grupp1
  labels:
    app: yaser-guestbook
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yaser-frontend
  template:
    metadata:
      labels:
        app: yaser-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/ysalha2003/yaser-guestbook-argocd/frontend:4b2d95bcc02d65765ba4d03673fc2042617ad19a
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 96Mi
            cpu: 150m
          requests:
            memory: 48Mi
            cpu: 80m
---
apiVersion: v1
kind: Service
metadata:
  name: yaser-frontend
  namespace: grupp1
spec:
  ports:
  - port: 8080
  selector:
    app: yaser-frontend
