apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: yaser-frontend
  namespace: yaser-dev
  labels:
    app: yaser-guestbook
spec:
  to:
    kind: Service
    name: yaser-frontend
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
